
Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
	vb.memory = 1024
  vb.cpus = 2
  end

  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "bento/ubuntu-20.10"
	  wordpress.vm.network "public_network", ip: "192.168.0.20"
    wordpress.vm.provision "shell",
      inline: "sudo ln -s /usr/bin/python3 /usr/bin/python"
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "bento/ubuntu-20.10"
    mysql.vm.network "public_network", ip: "192.168.0.22"
    mysql.vm.provision "shell",
      inline: "sudo ln -s /usr/bin/python3 /usr/bin/python"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.network "public_network", ip: "192.168.0.21"
    ansible.vm.provision "shell",
       inline:  "sudo apt update && sudo apt install -y ansible"
  end
end
